### ISSUE TITLE
Make tabular data accessible via WFS

### ISSUE THREAD

**Issue by ridoo** [GeoNodeUserGroup-DE/geonode-dev-datapackage#11]
This should work already, but should be re-checked in combination with #3

**Comment by ridoo** [comment]
Just a comment: Some formats seems to expect spatial content (e.g. Shapefile or KML). See also my comment from #15 : 

> However, WFS download is set independently from that, so some unsupported download formats are still selectable then, like Shapefile or KML. Other formats like GeoJSON or GML are just fine.

@specka @mwallschlaeger you should decide if this is just ok for you. Please close or comment.

**Comment by ridoo** [comment]
* Double check if formats could be configured for a dedicated dataset
* Open:
  * What is needed, to make these formats work
  * Document what works and what does not

**Comment by ridoo** [comment]
Formats are part of the general `<ows:Operation name="GetFeature">` section and cannot be configured for a specific dataset.

Documentation:

* :red_circle: Shapefile works but is invalid when trying to open it
* :green_circle: GML variants
* :green_circle: GeoJSON
* :yellow_circle: KML works and XML has content. QGIS however, does not show any data

I would close this issue. @mwallschlaeger please decide if that kind of documentation is enough for now.

**Comment by mwallschlaeger** [comment]
@ridoo this is fine for me for now.
