### ISSUE TITLE
Task: thumbnail for tabular data

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/geonode-dev-datapackage#18]
currently nobody really looked on how the thumbnails of tabular data are looking or can be configured in the overview list of geonode.

**Comment by ridoo** [comment]
Currently, there is a `table-icon.jpg` shipped with the `importer_datapackage` module. However, this was more like testing things out and was not saved as thumbnail. With regard to #6 (here: avoid [automatic thumbnail](https://github.com/GeoNode/geonode/blob/582392ea88b38beb2243360f03c013309247d4f2/geonode/thumbs/utils.py#L219) creation via WMS) I take this up again in context of this issue as once a thumbnail is set, no WMS will be requested for an image.

TODOs:

- [ ] Set the `table-icon.jpg` by default for non-tabular datasets
- [ ] Remove the UI option to set a thumbnail based on WMS
- [ ] (optional) let the user upload a thumbnail alongside the actual data
