### ISSUE TITLE
A table corresponds to a dataset object in GeoNode

### ISSUE THREAD

**Issue by ridoo** [GeoNodeUserGroup-DE/geonode-dev-datapackage#2]
A table corresponds to a “dataset” object in GeoNode including metadata in the BonaRes schema: a table corresponds to a dataset object in GeoNode, so each table can have its own metadata in the integrated BonaRes metadata schema

Related: https://github.com/GeoNodeUserGroup-DE/importer-datapackage/issues/4

**Comment by mwallschlaeger** [comment]
as this can only be tested after integrating all changes geonode, geonode-mapstore-client, and contrib_datapackage into zalf-geonode by @mwallschlaeger this is issue is not part of the 52N sprint. I will remove it the 52N tag from this issue
