### ISSUE TITLE
Bug: Sharing a tabular dataset as using embeded link directs to the thumbnail of the dataset

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/geonode-dev-datapackage#27]
when following the *Share with people and groups* -> *Embed this Dataset* link we end up at the thumbnail image of a tabular dataset. I would have expected to find an embedded table. 

![image](https://github.com/user-attachments/assets/097c364e-3949-4f11-932b-31283f9d7e02)

**Comment by ridoo** [comment]
The startup logic within the embed-templates has to be updated here. I will have a look into it

**Comment by ridoo** [comment]
Fixed by handling custom routes during startup
