### ISSUE TITLE
Bug: forwarded to https://172.18.0.1/catalogue/#/map/$PK after editing metadata of map

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/geonode-dev-datapackage#28]
After opening a map only containing `tabular` datasets as tabular-collection (e.g. https://172.18.0.1/catalogue/#/tabular-collection/12) and editing metadata. After clicking update on metadata editor users get forwarded to to https://172.18.0.1/catalogue/#/maps/12

**Comment by ridoo** [comment]
Fixed redirect
