### ISSUE TITLE
public test instance

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/geonode-dev-datapackage#31]
to show the state of the `contrib_datapackage`to the [GeoNodeUserGroup-DE](https://github.com/GeoNodeUserGroup-DE) community a demo instance is required. Should be available for the next user group meeting at the 12th of September

**Comment by ridoo** [comment]
See https://github.com/GeoNodeUserGroup-DE/GN-development/issues/6#issuecomment-2290972482
