### ISSUE TITLE
Visualization of table data sets using a dedicated tabular view

### ISSUE THREAD

**Issue by ridoo** [GeoNodeUserGroup-DE/geonode-dev-datapackage#5]
Visualization of table data sets using a dedicated tabular view: Table data should not be displayed as a map but as a table when viewed.

**Comment by ridoo** [comment]
Previewing the tabular data is possible by using the [`TabularPreview` plugin](https://github.com/GeoNodeUserGroup-DE/geonode-mapstore-client/blob/33b45976bf96f7160d5ec23939f09df5d8263a34/geonode_mapstore_client/client/js/plugins/TabularPreview.jsx#L77) of the geonode-mapstore-client. The tabular preview has [a dedicated route](https://github.com/GeoNodeUserGroup-DE/geonode-mapstore-client/blob/33b45976bf96f7160d5ec23939f09df5d8263a34/geonode_mapstore_client/client/js/utils/AppRoutesUtils.js#L86-L97), e.g. `/catalogue/#/tabular/6`.

I updated [the configuration section](https://github.com/GeoNodeUserGroup-DE/importer-datapackage#configuration) with regard to the `TabularPreview`.

@mwallschlaeger @specka If this resolves what you need, this issue could be closed.

**Comment by mwallschlaeger** [comment]
@ridoo does this mean no changes to the geonode-mapstore-client are required?

**Comment by ridoo** [comment]
@mwallschlaeger the geonode-mapstore-plugin already provides the `TabularPreview` plugin which can be configured in the `localConfig.json`. The plugin had been developed in the Thünen SEP1.

**Comment by ridoo** [comment]
* DetailPanel noch mal prüfen

**Comment by ridoo** [comment]
Was just incomplete configuration. However, the thumbnail/icon is not displayed properly:

![image](https://github.com/GeoNodeUserGroup-DE/geonode-dev-datapackage/assets/881756/7dd7d369-6901-4673-9ac9-158e1c082749)

@mwallschlaeger @specka please decide, if this is ok to you. Maybe we find the time afterwards to fix the thumbnail/icon issue?!
